CodeForAfrica/PromiseTracker

- package.json
- yarn.lock
Upgrade new, backward & security dependencies.
N/A
> [Chore] Dependencies

- src/components/PromiseChart/index.js
- src/components/PromiseChart/useStyles.js
- src/lib/check/index.js
Render charts for Promises that have multiple chart links
Fixes [#176408838](https://www.pivotaltracker.com/n/projects/2204613/stories/176408838)
> [Fix] Render multiple charts

- src/components/Navigation/DesktopNavigation/MenuButton.js
- src/components/Navigation/DesktopNavigation/NavigationButton.js
Add hover state to Analysis button
Fixes [176627466](https://www.pivotaltracker.com/story/show/176627466)
> Analysis Button Hover Fix

- src/components/Navigation/MobileNavigation/NavigationList.js
- src/components/PromiseTimeline/TimelineEvent.js
> [Feedback Fix]Change border color 

- src/components/PromiseTimeline/TimelineEvent.js
- src/pages/analysis/resources.js
> [Feedback Fix]Add resources page

- src/components/PromiseTimeline/TimelineEvent.js
- src/components/Share/index.js
- src/components/Share/useStyles.js
> [Feedback Fix] Hover on share button

- src/components/Promise/Radar.js
- src/components/Promise/index.js
- src/components/Promise/useStyles.js
> [Feedback Fix]Update promise sidebar

- src/components/Hero/ProfileChart/DesktopChart/index.js
- src/components/Hero/ProfileChart/MobileChart/MobileSvgChart.js
- src/components/Hero/ProfileChart/MobileChart/ProgressChart.js
- src/components/Hero/ProfileChart/MobileChart/index.js
- src/components/Hero/ProfileChart/ProfileDetails.js
- src/components/Hero/ProfileChart/RectChart/RectSvgChart.js
- src/components/Hero/ProfileChart/RectChart/index.js
- src/config.js
- src/lib/check/index.js
- src/theme/index.js
> [Feedback Fix] Update site statuses

- src/components/ActNow/index.js
- src/components/ErrorPage/index.js
- src/components/Newsletter/index.js
- src/pages/act-now.js
> [Feedback Fix] Replace Pixilated images

- yarn.lock
Upgrade backward compatible dependencies
N/A
N/A
> [Chore] Dependenices

- src/components/Promises/Filter/FilterButton.js
- src/components/Promises/Filter/useStyles.js
- src/components/Promises/Sort.js
- src/components/Promises/index.js
- src/components/Promises/useStyles.js
> [Feedback Fix] Update promise filter

- src/components/Article/index.js
- src/components/Article/useStyles.js
- src/lib/wp/index.js
- src/pages/analysis/articles/[slug].js
> Fix pixilated images

- src/components/KeyPromises/index.js
- src/lib/check/index.js
- src/lib/server/index.js
- src/pages/index.js
Fixes # Remove dots if key promise is one
`No Promises`
`One Promise`
> Update Key promises MobileStepper Dots

- src/lib/wp/index.js
- src/pages/about/[slug].js
- src/pages/analysis/articles/[slug].js
- src/pages/api/preview.js
> Add preview mode working on nextjs

- src/pages/about/[slug].js
- src/pages/analysis/articles/[slug].js
Enable Fallback for preview mode
Fixes # (N/A)
> Enable fallback

- package.json
- src/components/Page/Base.js
- src/components/Promise/AuthorAtribution.js
- src/components/Promise/Narative.js
- src/components/PromiseChart/index.js
- src/config.js
- yarn.lock
Fixes the following bugs:
1. Double scroll behaviour noted on Firefox.
2. Google fonts error after version bump.
3. Throws error when no charts are present.
> [Fix] Firefox, Google and Chart Bugs

- .eslintrc.json
- .husky/pre-commit
- README.md
- package.json
- src/components/AboutPage/Partners.js
- src/components/Article/index.js
- src/components/Copyright.js
- src/components/Footer/index.js
- src/components/Footer/useStyles.js
- src/components/Hero/ProfileChart/DesktopInfoStatusPopover.js
- src/components/Hero/ProfileChart/MobileInfoStatusPopover.js
- src/components/Link/Button.js
- src/components/Link/index.js
- src/components/Partners/index.js
- src/components/Promises/index.js
- src/config.js
- src/lib/check/index.js
- src/pages/_app.js
- yarn.lock
> [Chore] Prepare for actNOW API Integration

- src/components/ActNowPage/index.js
- src/components/ActionDialog/index.js
- src/components/ActionDialog/useStyles.js
- src/components/IndividualRegistrationDialog/index.js
- src/components/RegistrationDialog/index.js
- src/components/RegistrationDialog/useStyles.js
- src/pages/act-now.js
Add registration dialog for user to choose whether to register an individual or organisation.
> [Feature] Registration Dialog

- src/components/IndividualRegistrationForm/index.js
- src/pages/api/accounts/index.js
actNOW API path has changed to versioned format. This PR updates registration form to use the new end point.
N/A
> [HotFix] actNOW API path

- src/components/ActNowPage/index.js
- src/components/ActNowPage/useStyles.js
- src/components/ActNowSummary/index.js
- src/components/SuggestPromise/index.js
- src/components/SuggestPromise/useStyles.js
- src/pages/act-now.js
- src/pages/api/accounts/index.js
- Adds ActNow summary component
- Adds ActNow promise suggestion component.
- 
> Ft ActNow Summary

- .gitignore
- src/components/ActNowPage/index.js
- src/components/ActNowPage/useStyles.js
- src/components/Form/useStyles.js
- src/components/LoginForm/Form.js
- src/components/LoginForm/index.js
- src/components/LoginForm/useStyles.js
- src/lib/actnow/index.js
- src/pages/api/auth/[...nextauth].js
- src/theme/index.js
Add Act Now Sign In Form
https://user-images.githubusercontent.com/23483005/151206650-76da3e8c-5ade-4b85-8f7d-fc1b6ae26482.mp4
> Sign In with actNOW

- src/components/Promises/index.js
This PR sorts the promise by promise deadline. It allows for addition using the google sheet
> Handle Promise Sort

- src/pages/promises/[...slug].js
This PR fixes the navigation on promise page
> [hotfix] Show promise page header

- src/components/Promise/index.js
- src/components/Promise/useStyles.js
- src/pages/promises/[...slug].js
> [Feature] Add image overlay and Border

- src/components/ActNowCard/PetitionCard.js
> [Feature] Start/Join a Petition re-direct

- src/components/Navigation/DesktopNavigation/index.js
- src/components/PostCardGrid/index.js
- src/components/PostCardGrid/useStyles.js
- src/components/Promise/useStyles.js
Fix Navigation Alignment, Title, Promise Grid Alignment
> [Fix] Navigation, Promises, Promise

- src/pages/promises/index.js
> [Fix] Empty Cetegories

- src/pages/500.js
- src/pages/api/auth/[...nextauth].js
> [Feature] Add 500 page

- src/components/ActNowPage/index.js
- src/components/ActNowPage/useStyles.js
> [Fix] Fix space between sections in ActNow

- src/components/Promises/Sort.js
- src/components/Promises/useStyles.js
Fixes # 181432069
##Current
##Fix
> [Fix]Update button styles for promise page

- src/components/ActNowPage/useStyles.js
- src/components/IndividualRegistrationForm/Form.js
> [FIX] Fix UI issues

- .github/workflows/main.yml
> Fix the build-arg step

- package.json
Bump version to v0.2.1-alpha.1
> Bump version to v0.2.0-alpha.2

- contrib/dokku/Dockerfile
Bump docker version to v0.2.0-alpha.2
> Bump docker version to v0.2.0-alpha.2

- contrib/dokku/Dockerfile
- package.json
Bump to version v0.2.0-alpha.3
> Bump to version v0.2.0-alpha.3

- contrib/dokku/Dockerfile
- package.json
Bump to version v0.2.0-alpha.5
> Bump to version v0.2.0-alpha.5

- .env.example
- package.json
- pnpm-lock.yaml
- src/collections/Documents.ts
- src/collections/Extractions.ts
- src/collections/Media.ts
- src/collections/Users.ts
- src/globals/Settings.ts
- src/payload-types.ts
- src/payload.config.ts
- src/utils/locales.ts
This PR add localisation support to the app.
Fixes #413
> Chore: Multilingual Support

- src/app/(frontend)/[...slugs]/page.tsx
- src/blocks/Hero/index.ts
- src/components/Hero/index.tsx
- src/components/PoliticalEntityList.tsx
- src/lib/data/politicalEntities.ts
- src/payload-types.ts
- Add promiseLabel field to HeroBlock interface
- Replace extractionCounts with promiseCounts in components
- Refactor status resolution logic to work with promises instead of extractions
- Update default values for promise tracking fields
> feat(hero): add promise tracking functionality and refactor status resolution

- src/app/(frontend)/[...slugs]/page.tsx
- src/app/(frontend)/[entitySlug]/promises/[promiseId]/page.tsx
- src/app/api/meedan-sync/route.ts
- src/components/Navigation/index.tsx
- src/lib/domain.ts
- src/payload.config.ts
- src/workflows/airtableWorkflow.ts
- src/workflows/meedanWorkflow.ts
This PR introduces new ways to navigate the site
- When a tenant only has one entity, navigate to the entity
- Clicking on the logo should redirect the user to the tenant selection page
> feat(navigation): Domain Navigation fix
